server:
  servlet:
    context-path: /pracSPB
#  server.port 可以透過 db 的 PROPERTIES_CONFIG 取得 (h2 db 無法使用)
  port: 8089

spring:
  application:
    name: practice-springboot
# default profile will be h2
  profiles:
    include: swagger
    active: h2
# depend on db PROPERTIES_CONFIG, stay code here to conveniently understand
mail:
  smtp:
    host: smtp.gmail.com
    port: 587
    auth: true
    starttls:
      enable: true
    EnableSSL:
      enable: true
  send:
    name: testSender
    address: workchiu65@gmail.com
    password: work2455
  debug: true

