INSERT INTO TEST_TABLE_ENTITY1(ID, VAR1, VAR2)
VALUES(SEQ_TTBE1.NEXTVAL, 'variable1-1', 'variable1-2');

INSERT INTO TEST_TABLE_ENTITY1(ID, VAR1, VAR2)
VALUES(SEQ_TTBE1.NEXTVAL, 'variable2-1', 'variable2-2');

INSERT INTO TEST_TABLE_ENTITY1(ID, VAR1, VAR2)
VALUES(SEQ_TTBE1.NEXTVAL, 'variable3-1', 'variable3-2');